apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    spec:
      containers:
      - name: react
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}